# Generated by Django 4.2.3 on 2023-07-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
